server:
  port: 8901
spring:
   application:
    name: microservice-provider-movie
    
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:7001/eureka 
  instance:
    prefer-ip-address: true 
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  
